# Book settings
title: "Física Mecánica"
author: "Equipo docente, con adaptación basada en material de Morten Hjorth-Jensen y Scott Pratt"
copyright: "2026"
only_build_toc_files: true
exclude_patterns:
  - .venv/**
  - _build
  - .DS_Store
  - references/**

execute:
  execute_notebooks: off

html:
  home_page_in_navbar: false
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false

sphinx:
  config:
    language: es
    myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - html_admonition
  extra_extensions:
    - sphinx_proof
